<?php

namespace App\Models;

use App\Traits\HasCompany;
use App\Scopes\ActiveScope;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class DealerLedgerVoucher extends BaseModel
{
    use HasCompany;

    protected $table = 'dealer_ledger_vouchers';

    protected $fillable = [
        'company_id',
        'branch_id',
        'dealer_id',
        'voucher_number',
        'type',
        'amount',
        'entry_type',
        'date',
        'remarks',
        'created_by',
        'is_voided',
        'voided_at',
    ];

    protected $casts = [
        'date' => 'datetime',
        'amount' => 'float',
        'is_voided' => 'boolean',
        'voided_at' => 'datetime',
    ];

    /**
     * Get the company associated with the voucher.
     */
    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class, 'company_id');
    }

    /**
     * Get the dealer associated with the voucher.
     */
    public function dealer(): BelongsTo
    {
        return $this->belongsTo(User::class, 'dealer_id')->withoutGlobalScope(ActiveScope::class);
    }

    /**
     * Get the user who created the voucher.
     */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by')->withoutGlobalScope(ActiveScope::class);
    }

    /**
     * Get the ledger entries generated by this voucher.
     */
    public function ledgerEntries(): HasMany
    {
        return $this->hasMany(DealerLedger::class, 'voucher_id');
    }
}
